---
title: "Dr. B's Leaderboard"
author: "Author: Vineel Nekkanti"
format: 
  dashboard: 
    logo: "images/niu_cob_logo.png"
    orientation: rows
---
<div style="display: flex; justify-content: space-between;">
  <div>Welcome to Dr. B's Class Participation Leader board.</div>
  <div>Updated on: `r format(Sys.Date(), '%B %d, %Y')`</div>
</div>

```{r setup, include=FALSE}
# Load necessary libraries
library(readr)
library(knitr)
library(tidyverse)
library(readxl)
library(dplyr)


# Data pre-processing
data <- read_excel("files/students_participation_tracker_BP.xlsx", sheet="Sheet1")
data <- data |> select(4:19) |> 
  rename(week_1 = "Week1_activities [Total Pts: 100 Score] |2715291",
         week_2 = "Week2_activities [Total Pts: 100 Score] |2715292",
         week_3 = "Week3_activities [Total Pts: 100 Score] |2715293",
         week_6 = "Week6_activities [Total Pts: 100 Score] |2993622",
         week_7 = "Week7_activities [Total Pts: 100 Score] |2715295",
         week_11 = "Week11_activities [Total Pts: 100 Score] |2779117",
         week_13 = "Week13_Activities [Total Pts: 100 Score] |2779113",
         tech_test = "Technology test [Total Pts: 6 Score] |2694609",
         preliminary_survey = "Preliminary survey",
         midterm_survey = "Midterm survey",
         exit_survey = "Exit Survey",
         in_class_participation = "In-class participation",
         teams_participation = "Teams participationon 100") |> 
  mutate("Weekly Activity Overall" = week_1+week_2+week_3+week_6+week_7+week_11+week_13,
         "Survey/Poll/Tech. Test" = tech_test+preliminary_survey+midterm_survey+exit_survey,
         "In-Class Participation" = in_class_participation,
         "Teams Participation" = teams_participation
         )
# Displaying the Overall Student data
overall_student_data <- data |> 
  select(1,16) |> 
  arrange(desc(`Total Points`)) |> 
  mutate(Rank = row_number(), Points = round(`Total Points`, 2)) |> 
  select(Rank, Name=1,Points) |> 
  filter(!is.na(Name))

# Displaying the weekly data
weekly_activity_data <- data |> 
  select(1,17) |> 
  arrange(desc(`Weekly Activity Overall`)) |> 
  mutate(Rank = row_number(), Points = round(`Weekly Activity Overall`, 2)) |> 
  select(Rank, Name=1,Points) |> 
  filter(!is.na(Name))

# Displaying the Survey/Poll/Technology Test data
survey_poll_techtest_data <- data |> 
  select(1,18) |> 
  arrange(desc(`Survey/Poll/Tech. Test`)) |>
  mutate(Rank = row_number(), Points = round(`Survey/Poll/Tech. Test`, 2)) |> 
  select(Rank, Name=1,Points) |> 
  filter(!is.na(Name))

# Displaying the In-Class Participation data
in_class_participation_data <- data |> 
  select(1,13) |> 
  arrange(desc(`in_class_participation`)) |> 
  mutate(Rank = row_number(), Points = round(`in_class_participation`, 2)) |> 
  select(Rank, Name=1,Points) |> 
  filter(!is.na(Name))

# Displaying the Teams Participation data
teams_participation_data <- data |> 
  select(1,14) |> 
  arrange(desc(`teams_participation`)) |> 
  mutate(Rank = row_number(), Points = round(`teams_participation`, 2)) |>
  select(Rank, Name=1,Points) |> 
  filter(!is.na(Name))

# Displaying the Professionalism data
professionalsim_data <- data |> 
  select(1,15) |> 
  arrange(desc(Professionalism)) |>
  mutate(Rank = row_number(), Points = round(`Professionalism`, 2)) |> 
  select(Rank, Name=1,Points) |> 
  filter(!is.na(Name))

```

## Row {.tabset}

#### P

```{r}
kable(overall_student_data)
```

#### W

```{r}
kable(weekly_activity_data)
```

#### I

```{r}
kable(in_class_participation_data)
```

#### T

```{r}
kable(teams_participation_data)
```

#### Pr

```{r}
kable(professionalsim_data)
```

#### O

```{r}
kable(survey_poll_techtest_data)
```

```{r, echo=FALSE, results='asis'}
# Inject JavaScript to check authentication status and redirect if necessary
cat(htmltools::HTML('<script>
if (localStorage.getItem("authenticated") !== "true") {
    window.location.href = "index.html";
}
</script>'))

```
